name: build and push
on: 
  push:
    branches: main
env:
  configmap_image: docker.pkg.github.com/${{ github.repository }}/configmap-reload
jobs:
  build-and-push:
    name: Build and push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set version
        run: |
          echo "CONFIGMAP_IMAGE=${configmap_image}:$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker build . --tag $CONFIGMAP_IMAGE --tag ${configmap_image}:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $CONFIGMAP_IMAGE
      